# Generated by Django 5.1.7 on 2025-03-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('institution', models.CharField(max_length=150, verbose_name='Место обучения')),
                ('timestamp', models.DateTimeField(verbose_name='Время ответа')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_title', models.CharField(max_length=255, verbose_name='Преимущество')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='survey.surveyresponse')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
