# Generated by Django 5.1.7 on 2025-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время ответа'),
        ),
    ]
