# Generated by Django 5.1.7 on 2025-03-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyresponse_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedbenefit',
            old_name='benefit_title',
            new_name='benefit',
        ),
    ]
