# Generated by Django 5.1.7 on 2025-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_benefit_title_selectedbenefit_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
